// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/car_manufacturer.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ManufacturerServiceClient is the client API for ManufacturerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManufacturerServiceClient interface {
	CreateManufacturer(ctx context.Context, in *CreateManufacturerRequest, opts ...grpc.CallOption) (*Manufacturer, error)
}

type manufacturerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManufacturerServiceClient(cc grpc.ClientConnInterface) ManufacturerServiceClient {
	return &manufacturerServiceClient{cc}
}

func (c *manufacturerServiceClient) CreateManufacturer(ctx context.Context, in *CreateManufacturerRequest, opts ...grpc.CallOption) (*Manufacturer, error) {
	out := new(Manufacturer)
	err := c.cc.Invoke(ctx, "/pb.ManufacturerService/CreateManufacturer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManufacturerServiceServer is the server API for ManufacturerService service.
// All implementations must embed UnimplementedManufacturerServiceServer
// for forward compatibility
type ManufacturerServiceServer interface {
	CreateManufacturer(context.Context, *CreateManufacturerRequest) (*Manufacturer, error)
	mustEmbedUnimplementedManufacturerServiceServer()
}

// UnimplementedManufacturerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedManufacturerServiceServer struct {
}

func (UnimplementedManufacturerServiceServer) CreateManufacturer(context.Context, *CreateManufacturerRequest) (*Manufacturer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateManufacturer not implemented")
}
func (UnimplementedManufacturerServiceServer) mustEmbedUnimplementedManufacturerServiceServer() {}

// UnsafeManufacturerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManufacturerServiceServer will
// result in compilation errors.
type UnsafeManufacturerServiceServer interface {
	mustEmbedUnimplementedManufacturerServiceServer()
}

func RegisterManufacturerServiceServer(s grpc.ServiceRegistrar, srv ManufacturerServiceServer) {
	s.RegisterService(&ManufacturerService_ServiceDesc, srv)
}

func _ManufacturerService_CreateManufacturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateManufacturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManufacturerServiceServer).CreateManufacturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ManufacturerService/CreateManufacturer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManufacturerServiceServer).CreateManufacturer(ctx, req.(*CreateManufacturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManufacturerService_ServiceDesc is the grpc.ServiceDesc for ManufacturerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManufacturerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ManufacturerService",
	HandlerType: (*ManufacturerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateManufacturer",
			Handler:    _ManufacturerService_CreateManufacturer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/car_manufacturer.proto",
}
